repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.22.1
    hooks:
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.thetornad0.", "--strict", "--"]
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
  
